theme: minima
title: ShjdshyBlog
email: shjdness@outlook.com
description: Just To Record Something
baseurl: "/ShjdshyBlog"
url: "https://shjdness.github.io"


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Your Name"
  - scope:
      path: "" # 对所有根目录下的文件
    values:
      layout: "default" # 默认使用 default 布局